# Generated by Django 2.2 on 2020-11-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote_dash_app', '0002_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quoted_by',
            new_name='author',
        ),
    ]
